include /etc/nginx/modules-enabled/*.conf;

worker_processes auto;

events {
    worker_connections 4096;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record off;
        }
    }
}

http {
    limit_conn_zone $binary_remote_addr zone=stream_conn:10m;
    limit_req_zone $binary_remote_addr zone=stream_req:10m rate=20r/s;

    server {
        listen 8080;

        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }

        location /live {
            limit_conn stream_conn 10;
            limit_req zone=stream_req burst=40 nodelay;
            add_header Access-Control-Allow-Origin *;
        }
    }
}
