services:
  web-backend:
    build:
      context: .
    container_name: iot-web-backend
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./app:/app/app
    restart: unless-stopped
